service:
  name: sls-05-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-2

functions:
  auth:
    handler: index.auth
    cors: true

  public:
    handler: index.getToken
    events:
      - http:
          path: api/token
          method: post
          cors: true

  private:
    handler: index.getUsers
    events:
      - http:
          path: api/users
          method: get
          authorizer: auth
          cors: true

